### ISSUE TITLE
文件权限被改变

### ISSUE THREAD

**Issue by scruel** [pymumu/smartdns#1755]
**问题现象**
配置增加 `conf-file` 或 `cache-file` 的配置后，
`./conf/app.ini` 文件的权限总被改为 root
`./` 文件夹目录的权限和所有者也老是变
建议能读写就不要改 owner:group 了
```
bind [::]:53

cache-persist no
server 114.114.114.114
conf-file /etc/smartdns/smartdns.cache.conf
```

**运行环境**
```
version: '3'

services:
  smartdns:
    container_name: smartdns
    image: pymumu/smartdns:latest
    restart: always
    network_mode: host
    volumes:
      - ./:/etc/smartdns
```
